---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-distributed
  namespace: loki

spec:
  interval: 5m
  releaseName: loki-distributed
  targetNamespace: loki

  chart:
    spec:
      chart: loki-distributed
      version: "0.28.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      interval: 1m
