---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki-promtail
  namespace: loki-distributed
spec:
  interval: 5m
  releaseName: loki-promtail
  targetNamespace: loki-distributed
  maxHistory: 30
  chart:
    spec:
      chart: promtail
      version: "2.0.0"
      sourceRef:
        kind: HelmRepository
        name: loki
        namespace: flux-system
      interval: 1m

  values:

    secrets:
      loki-distributed-basic-auth:
        username: BASIC_AUTH_USERNAME
        password: BASIC_AUTH_PASSWORD

    image:
      repository: grafana/promtail
      tag: 2.0.0
      pullSecrets:
        - docker-registry
      pullPolicy: IfNotPresent

    resources:
      limits:
        cpu: "100m"
        memory: 128Mi
      requests:
        cpu: "50m"
        memory: 128Mi

    priorityClassName: "high-priority"

    podLabels:
      app.kubernetes.io/name: loki-promtail
      app.kubernetes.io/instance: loki-promtail

    config:
      client:
        url: http://gateway.loki.wine.com.br/loki/api/v1/push
        tenant_id: "hmg-dev"

        # Maximum wait period before sending batch
        batchwait: 1s
        # Maximum batch size to accrue before sending, unit is byte
        batchsize: 102400

        # Maximum time to wait for server to respond to a request
        timeout: 10s

        backoff_config:
          # Initial backoff time between retries
          min_period: 500ms
          # Maximum backoff time between retries
          max_period: 5m
          # Maximum number of retries when sending batches, 0 means infinite retries
          max_retries: 20

        # The labels to add to any time series or alerts when communicating with loki
        external_labels: {}

        basic_auth:
          username: BASIC_AUTH_USERNAME
          password: BASIC_AUTH_PASSWORD

      server:
        http_listen_port: 3101

      positions:
        filename: /run/promtail/positions.yaml

      target_config:
        # Period to resync directories being watched and files being tailed
        sync_period: 10s

    pipelineStages:
      - docker: {}