apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo-4
  namespace: app
  annotations:
    fluxcd.io/automated: "true"
spec:
  chart:
    repository: https://stefanprodan.github.io/podinfo
    name: podinfo
    version: 3.2.0 
  # containers:
  # - name: podinfod
  #   image: ghcr.io/stefanprodan/podinfo:5.0.0 # {"$imagepolicy": "flux-system:podinfo"}
