apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: podinfo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: podinfo
    spec:
      containers:
      - name: podinfo
        image: ghcr.io/stefanprodan/podinfo:3.2.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi