apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo-2
  namespace: app
spec:
  interval: 4m
  releaseName: podinfo-2
  targetNamespace: app

  chart:
    spec:
      chart: podinfo
      version: "3.2.0"
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m