apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo 
  namespace: app
spec:
  interval: 4m
  releaseName: podinfo
  targetNamespace: app

  chart:
    spec:
      chart: podinfo
      version: "5.2.0" #versao certa 3.2.0
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system 
spec:
  url: https://stefanprodan.github.io/podinfo
  interval: 1m
