apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: monitoring
spec:
  chart:
    repository: https://prometheus-community.github.io/helm-charts
    name: prometheus
    version: 13.6.0