---
apiVersion: image.toolkit.fluxcd.io/v1alpha1
kind: ImageRepository
metadata:
  name: redis
  namespace: flux-system
spec:
  image: docker.io/beatrizafonso/redis
  interval: 1m0s

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: docker.io/beatrizafonso/redis:1.1.0 # {"$imagepolicy": "flux-system:redis"}
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
