apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- .sourceignore
- automation/my-app-auto.yaml
- automation/redis-registry.yaml
- automation/redis-policy.yaml
- flux-system
- namespaces/app.yaml
- namespaces/flux.yaml
- namespaces/monitoring.yaml
- notification/release.yaml
- podinfo-2/helm-release.yaml
- podinfo-3/helm-release.yaml
- podinfo-4/helm-release.yaml
- prometheus/helm-release.yaml
- grafana/helm-release.yaml
- redis/helm-release.yaml